## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from google.colab import files

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [ ]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df.groupby(["APPLICATION_TYPE"]).size().sort_values(ascending=False)
application_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T29        2
T15        2
T17        1
dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_type_counts[application_type_counts < 500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df.groupby(["CLASSIFICATION"]).size().sort_values(ascending=False)
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2190        1
C2380        1
C2500        1
C2561        1
C8210        1
Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_greater_than_1 = classification_counts[classification_counts > 1]

# Display the filtered classification counts
classification_counts_greater_than_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1278       10
C1238       10
C1235        9
C1237        9
C7210        7
C1720        6
C4100        6
C2400        6
C1600        5
C1257        5
C2710        3
C1260        3
C0           3
C1267        2
C1246        2
C1256        2
C3200        2
C1234        2
dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts < 1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_encoded = pd.get_dummies(application_df)

In [ ]:
# Split our preprocessed data into our features and target arrays
X = application_df_encoded.drop(columns=['IS_SUCCESSFUL'])
y = application_df_encoded['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=X_train_scaled.shape[1]))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 80)                  │           3,520 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 30)                  │           2,430 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,981 (23.36 KB)

 Trainable params: 5,981 (23.36 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
nn.compile(optimizer='adam',
           loss='binary_crossentropy',
           metrics=['accuracy'])

In [ ]:
# Train the model
history = nn.fit(X_train_scaled, y_train,
                 epochs=100,
                 batch_size=32,
                 validation_data=(X_test_scaled, y_test))

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.7039 - loss: 0.5855 - val_accuracy: 0.7291 - val_loss: 0.5592
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7309 - loss: 0.5526 - val_accuracy: 0.7237 - val_loss: 0.5571
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7302 - loss: 0.5528 - val_accuracy: 0.7317 - val_loss: 0.5594
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7289 - loss: 0.5515 - val_accuracy: 0.7284 - val_loss: 0.5546
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7335 - loss: 0.5423 - val_accuracy: 0.7290 - val_loss: 0.5541
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7361 - loss: 0.5448 - val_accuracy: 0.7318 - val_loss: 0.5542
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7321 - loss: 0.5485 - val_accuracy: 0.7327 - val_loss: 0.5540
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7281 - loss: 0.5495 - val_accuracy: 0.7292 - val_loss: 0.5543
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7350 - loss: 0.5455 - val_accuracy: 0.7284 - val_loss: 0.5548
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7287 - loss: 0.5504 - val_accuracy: 0.7291 - val_loss: 0.5529
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7357 - loss: 0.5437 - val_accuracy: 0.7296 - val_loss: 0.5519
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7362 - loss: 0.5417 - val_accuracy: 0.7298 - val_loss: 0.5535
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7357 - loss: 0.5433 - val_accuracy: 0.7259 - val_loss: 0.5525
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7394 - loss: 0.5407 - val_accuracy: 0.7297 - val_loss: 0.5551
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7325 - loss: 0.5450 - val_accuracy: 0.7308 - val_loss: 0.5549
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7382 - loss: 0.5430 - val_accuracy: 0.7318 - val_loss: 0.5505
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7327 - loss: 0.5459 - val_accuracy: 0.7319 - val_loss: 0.5559
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7335 - loss: 0.5438 - val_accuracy: 0.7279 - val_loss: 0.5528
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7398 - loss: 0.5371 - val_accuracy: 0.7297 - val_loss: 0.5524
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7402 - loss: 0.5360 - val_accuracy: 0.7278 - val_loss: 0.5543
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7342 - loss: 0.5467 - val_accuracy: 0.7317 - val_loss: 0.5525
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7380 - loss: 0.5427 - val_accuracy: 0.7271 - val_loss: 0.5582
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7357 - loss: 0.5481 - val_accuracy: 0.7328 - val_loss: 0.5550
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7382 - loss: 0.5377 - val_accuracy: 0.7319 - val_loss: 0.5544
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7359 - loss: 0.5417 - val_accuracy: 0.7310 - val_loss: 0.5544
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7380 - loss: 0.5386 - val_accuracy: 0.7276 - val_loss: 0.5534
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7359 - loss: 0.5424 - val_accuracy: 0.7325 - val_loss: 0.5538
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7379 - loss: 0.5350 - val_accuracy: 0.7289 - val_loss: 0.5527
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7358 - loss: 0.5427 - val_accuracy: 0.7284 - val_loss: 0.5528
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7361 - loss: 0.5398 - val_accuracy: 0.7282 - val_loss: 0.5548
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7324 - loss: 0.5448 - val_accuracy: 0.7262 - val_loss: 0.5532
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7461 - loss: 0.5304 - val_accuracy: 0.7252 - val_loss: 0.5542
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7384 - loss: 0.5392 - val_accuracy: 0.7299 - val_loss: 0.5568
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7384 - loss: 0.5382 - val_accuracy: 0.7325 - val_loss: 0.5566
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7434 - loss: 0.5339 - val_accuracy: 0.7321 - val_loss: 0.5537
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7339 - loss: 0.5429 - val_accuracy: 0.7313 - val_loss: 0.5534
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7332 - loss: 0.5411 - val_accuracy: 0.7290 - val_loss: 0.5552
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7329 - loss: 0.5429 - val_accuracy: 0.7269 - val_loss: 0.5560
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7389 - loss: 0.5359 - val_accuracy: 0.7292 - val_loss: 0.5539
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7400 - loss: 0.5364 - val_accuracy: 0.7334 - val_loss: 0.5539
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7412 - loss: 0.5361 - val_accuracy: 0.7300 - val_loss: 0.5561
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7401 - loss: 0.5341 - val_accuracy: 0.7308 - val_loss: 0.5546
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7355 - loss: 0.5396 - val_accuracy: 0.7298 - val_loss: 0.5544
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7413 - loss: 0.5341 - val_accuracy: 0.7314 - val_loss: 0.5566
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7363 - loss: 0.5407 - val_accuracy: 0.7283 - val_loss: 0.5550
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7374 - loss: 0.5379 - val_accuracy: 0.7296 - val_loss: 0.5548
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7353 - loss: 0.5419 - val_accuracy: 0.7255 - val_loss: 0.5579
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7384 - loss: 0.5397 - val_accuracy: 0.7266 - val_loss: 0.5543
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7392 - loss: 0.5360 - val_accuracy: 0.7286 - val_loss: 0.5547
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7366 - loss: 0.5416 - val_accuracy: 0.7297 - val_loss: 0.5553
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7433 - loss: 0.5349 - val_accuracy: 0.7282 - val_loss: 0.5559
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7378 - loss: 0.5374 - val_accuracy: 0.7290 - val_loss: 0.5564
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7395 - loss: 0.5345 - val_accuracy: 0.7279 - val_loss: 0.5567
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7400 - loss: 0.5353 - val_accuracy: 0.7293 - val_loss: 0.5562
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7402 - loss: 0.5369 - val_accuracy: 0.7304 - val_loss: 0.5569
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7374 - loss: 0.5388 - val_accuracy: 0.7317 - val_loss: 0.5577
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7351 - loss: 0.5433 - val_accuracy: 0.7313 - val_loss: 0.5575
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7420 - loss: 0.5342 - val_accuracy: 0.7304 - val_loss: 0.5584
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7420 - loss: 0.5367 - val_accuracy: 0.7284 - val_loss: 0.5596
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7417 - loss: 0.5333 - val_accuracy: 0.7282 - val_loss: 0.5576
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7327 - loss: 0.5430 - val_accuracy: 0.7276 - val_loss: 0.5587
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7389 - loss: 0.5350 - val_accuracy: 0.7297 - val_loss: 0.5587
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7355 - loss: 0.5394 - val_accuracy: 0.7304 - val_loss: 0.5596
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7359 - loss: 0.5359 - val_accuracy: 0.7312 - val_loss: 0.5568
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7404 - loss: 0.5360 - val_accuracy: 0.7300 - val_loss: 0.5580
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7451 - loss: 0.5275 - val_accuracy: 0.7287 - val_loss: 0.5575
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7376 - loss: 0.5394 - val_accuracy: 0.7293 - val_loss: 0.5581
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7392 - loss: 0.5349 - val_accuracy: 0.7286 - val_loss: 0.5580
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7405 - loss: 0.5334 - val_accuracy: 0.7254 - val_loss: 0.5577
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7376 - loss: 0.5385 - val_accuracy: 0.7273 - val_loss: 0.5605
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7379 - loss: 0.5382 - val_accuracy: 0.7273 - val_loss: 0.5592
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7399 - loss: 0.5367 - val_accuracy: 0.7276 - val_loss: 0.5593
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7425 - loss: 0.5340 - val_accuracy: 0.7286 - val_loss: 0.5602
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7432 - loss: 0.5350 - val_accuracy: 0.7310 - val_loss: 0.5588
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7437 - loss: 0.5322 - val_accuracy: 0.7278 - val_loss: 0.5593
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7450 - loss: 0.5301 - val_accuracy: 0.7284 - val_loss: 0.5589
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7425 - loss: 0.5346 - val_accuracy: 0.7293 - val_loss: 0.5588
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7389 - loss: 0.5389 - val_accuracy: 0.7278 - val_loss: 0.5585
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7463 - loss: 0.5299 - val_accuracy: 0.7291 - val_loss: 0.5587
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7419 - loss: 0.5287 - val_accuracy: 0.7279 - val_loss: 0.5600
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7361 - loss: 0.5388 - val_accuracy: 0.7268 - val_loss: 0.5601
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7385 - loss: 0.5316 - val_accuracy: 0.7254 - val_loss: 0.5585
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7412 - loss: 0.5334 - val_accuracy: 0.7273 - val_loss: 0.5620
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7389 - loss: 0.5358 - val_accuracy: 0.7308 - val_loss: 0.5589
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7416 - loss: 0.5343 - val_accuracy: 0.7315 - val_loss: 0.5590
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7366 - loss: 0.5371 - val_accuracy: 0.7298 - val_loss: 0.5582
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7453 - loss: 0.5292 - val_accuracy: 0.7305 - val_loss: 0.5603
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7391 - loss: 0.5355 - val_accuracy: 0.7282 - val_loss: 0.5596
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7442 - loss: 0.5328 - val_accuracy: 0.7287 - val_loss: 0.5601
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7420 - loss: 0.5310 - val_accuracy: 0.7248 - val_loss: 0.5619
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7388 - loss: 0.5376 - val_accuracy: 0.7252 - val_loss: 0.5626
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7448 - loss: 0.5324 - val_accuracy: 0.7285 - val_loss: 0.5607
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7445 - loss: 0.5311 - val_accuracy: 0.7300 - val_loss: 0.5596
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7434 - loss: 0.5312 - val_accuracy: 0.7284 - val_loss: 0.5597
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7391 - loss: 0.5345 - val_accuracy: 0.7278 - val_loss: 0.5616
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7436 - loss: 0.5312 - val_accuracy: 0.7278 - val_loss: 0.5598
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7426 - loss: 0.5324 - val_accuracy: 0.7285 - val_loss: 0.5609
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7415 - loss: 0.5337 - val_accuracy: 0.7286 - val_loss: 0.5616
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7421 - loss: 0.5331 - val_accuracy: 0.7261 - val_loss: 0.5610
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7387 - loss: 0.5346 - val_accuracy: 0.7289 - val_loss: 0.5599

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 1ms/step - accuracy: 0.7289 - loss: 0.5599
Loss: 0.5599035024642944, Accuracy: 0.728863000869751

In [ ]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")
# Download h5 file
files.download("AlphabetSoupCharity.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.